# docker-compose.yml
version: '2'
services:
  nginx:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./logs:/logs
      - ./server-proxy.conf:/usr/local/openresty/nginx/conf/server-proxy.conf
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ssl_data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: 'ericjwarren.com'
      SITES: 'wiki.ericjwarren.com=10.19.94.147:8001;*.ericjwarren.com=10.19.94.147:8002;'


volumes:
  ssl_data:
