version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: TE9MIGNyZWRzIGluIGdpdGh1Yg==
    ports:
      - 7000:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 7001:8080
